[workspace]
resolver = "2"
members = ["packages/*"]

[workspace.dependencies]
cosmwasm-std = "=1.1.9"

[patch.crates-io]
cosmwasm-std = { git = "https://github.com/Finschia/cosmwasm", tag = "v1.1.9+0.8.1" }
home = { git = "https://github.com/rust-lang/cargo.git", tag = "home-0.5.5" }
